### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by brendasalenave** [machinereading/frameBERT#1]
I am getting UnicodeDecodeError when loading frameBERT

```
>>> from frameBERT import frame_parser
2021-05-17 13:54:43.756497: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]\frameBERT\frame_parser.py", line 16, in <module>
    from frameBERT import target_identifier
  File "[...]\frameBERT\target_identifier.py", line 14, in <module>
    kfn = koreanframenet.interface(1.1)
  File "[...]\frameBERT\koreanframenet\koreanframenet.py", line 21, in __init__
    self.kfn_lus = json.load(f)
  File "[...]\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "[...]\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 34: character maps to <undefined>
```

**Comment by brendasalenave** [comment]
It is necessary to specify the `utf-8` encoding when opening files in the `koreanframenet.py` `init` function.
